### PR TITLE
Columnlabel merge

### PR DESCRIPTION
**Pull request by jjwesse**
Merge columnlabel feature branch into master

### CODE REVIEW

**Review by apigatto — CHANGES_REQUESTED** [review]
Determine why Pv02 ruler is missing.

**Review by apigatto — COMMENTED** [review]
When I try to run this branch I receive an error "Could not resolve '../../../mixwith.js/src/mixwith' from /workspaces/cmap-js/src/ui/layout/HorizontalLayout.js"

**Comment by nathanweeks** [comment]
@apigatto : while #118 is pending, need `git submodule init` followed by `git submodule update` the first time the repo is cloned

**Comment by apigatto** [comment]
Did that and now appears to be running smoothly.

**Review by apigatto — APPROVED** [review]

**Pull request merged**
