### PR TITLE
Mithril 2 update

### LINKED ISSUE #125: Upgrade to Mithril 2
https://mithril.js.org/changelog.html

### PR DESCRIPTION
**Pull request by That-Thing**
Updates mithril version to 2.

### CODE REVIEW

**Comment by jd-campbell** [comment]
@nathanweeks I am not sure if you want to review this.  I think you are the most qualified within the SoyBase group to review this.

**Comment by That-Thing** [comment]
Tests have been ported over to [Ospec](https://github.com/MithrilJS/ospec), and seem to run successfully.

**Comment by jd-campbell** [comment]
@That-Thing 
User Interface error occurs when I remove a map from the Mithril 2 update version.

Old Mithril Cmap-JS after removing pv_consensus and pv_genome
Screenshot 2024-08-22 at 18 55 51


Mithril 2 Cmap-JS after removing pv_consensus and pv_genome
Screenshot 2024-08-22 at 18 55 14

I will also submit this info to the issue tracker along with any other issues I find.

**Comment by That-Thing** [comment]
Fixed in latest commit

**Comment by That-Thing** [comment]
Fixing this seemed to have caused a test to fail. Working on fixing this.

**Review by maxglycine — CHANGES_REQUESTED** [review]
Simmon:
Looks like we are making progress.  I was able to "remove" the PV maps and that is good.  But when I scrolled/zoomed into a chromosomal region, the slider bar (turquoise bar) representing the zoom region on the gm_compostite map and the gm_genome map froze and I was not able to move it along the chromosomes.  I have seen this behavior before.  Sometimes it slides, sometimes it freezes.  I let it sit awhile to see if it would "catch up"  but it remained frozen.  I removed the gm_genome map and opened it again and the slider on the gm_composite map started to work when it was frozen before removing and replacing the gm_genome map. I am not sure what "gm_genome" means.  I was assuming what I was looking at was the gm_gwas map but it was the gm_genome map.  I note that gm_gwas was not available in the "ADD MAP" tool.  I am assuming that when it is finished that map set will be available.  You are doing great, you got one item fixed and when the zoom region is fixed hopefully we can merge it into main. @That-Thing @jd-campbell @StevenCannon-USDA

**Comment by That-Thing** [comment]
This seems to be behavior present in the Mithril 1.1.1 version as well. I'm going to create a separate issue for this.

**Review by jd-campbell — CHANGES_REQUESTED** [review]
I found another small thing that needs to be fixed:  
the light blue box on the left of the backbone - is supposed to move up and down the backbone once the user zooms in on a portion of the backbone.   

In the Mithril-2-update this light blue box **does not** move.

**Comment by jd-campbell** [comment]
@That-Thing  Lets talk about the status of this during the Cmap-JS meeting today.

**Comment by maxglycine** [comment]
@That-Thing Simon when is the meeting and could you send me a link

**Comment by That-Thing** [comment]
@maxglycine It was yesterday.

**Comment by That-Thing** [comment]
Ok everything seems to work, some tests just fail if the node version is <17 specifically in `DataSourceModel.test.js`  because of the config import. 

Are there any more issues or can I merge into main?

**Comment by nathanweeks** [comment]
> Ok everything seems to work, some tests just fail if the node version is <17 specifically in `DataSourceModel.test.js` because of the config import.

Node < 18 is EOL & the GitHub Actions workflow tests with Node 18, so no worries regarding that.

**Review by jd-campbell — APPROVED** [review]
@That-Thing  I used cmap-js via code space and found no new issues. Thank you for working on this.

**Pull request merged**
